<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>jms-messenger</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>business-logic</module>
        <module>dao-api</module>
        <module>docker</module>
        <module>docker-artemis</module>
        <module>domain</module>
        <module>server</module>
        <module>integration-tests</module>
        <module>jms-client</module>
        <module>jms-api</module>
        <module>dao</module>
    </modules>


    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>17</java.version>

        <plugin.maven.compiler.version>3.8.1</plugin.maven.compiler.version>
        <plugin.maven.jar.version>3.1.2</plugin.maven.jar.version>
        <plugin.maven.source.version>3.2.0</plugin.maven.source.version>
        <plugin.maven.resources.version>3.0.2</plugin.maven.resources.version>
        <plugin.surefire.version>2.22.1</plugin.surefire.version>

        <cs.bom.version>1.2.0-SNAPSHOT</cs.bom.version>
        <cs.commons.version>1.2.0-SNAPSHOT</cs.commons.version>

        <spring-boot.version>3.5.7</spring-boot.version>

        <!-- Docker Images versioning -->
        <cs.docker.image.tag>8.4</cs.docker.image.tag>

<!--        <msg.mysql.version.tag>${cs.docker.image.tag}</msg.mysql.version.tag>-->
<!--        <msg.mysql.version>docker.dev.jmsapp.com/cs-mysql:${msg.mysql.version.tag}</msg.mysql.version>-->

    </properties>




    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>


            <dependency>
                <groupId>org.example</groupId>
                <artifactId>business-logic</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.example</groupId>
                <artifactId>dao</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.example</groupId>
                <artifactId>dao-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.example</groupId>
                <artifactId>domain</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.example</groupId>
                <artifactId>jms-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.example</groupId>
                <artifactId>jms-client</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.example</groupId>
                <artifactId>server</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.hibernate.common</groupId>
                <artifactId>hibernate-commons-annotations</artifactId>
                <version>6.0.6.Final</version>
            </dependency>

<!--            &lt;!&ndash; https://mvnrepository.com/artifact/org.hibernate/hibernate-tools &ndash;&gt;-->
<!--            <dependency>-->
<!--                <groupId>org.hibernate</groupId>-->
<!--                <artifactId>hibernate-tools</artifactId>-->
<!--                <version>5.6.15.Final</version>-->
<!--            </dependency>-->


        </dependencies>
    </dependencyManagement>


    <dependencies>



<!--        <dependency>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-starter-web</artifactId>-->
<!--            <version>${spring-boot.version}</version>-->
<!--        </dependency>-->

<!--        Remove manual logging overrides Because Spring Boot starter already brings correct logging versions spring-data-jpa, hibernate-validator, jackson-annotations, etc-->
<!--        <dependency>-->
<!--            <groupId>org.slf4j</groupId>-->
<!--            <artifactId>slf4j-api</artifactId>-->
<!--            <version>2.0.12</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>ch.qos.logback</groupId>-->
<!--            <artifactId>logback-classic</artifactId>-->
<!--            <version>1.4.14</version>-->
<!--        </dependency>-->






<!--        <dependency>-->
<!--            <groupId>com.fasterxml.jackson.core</groupId>-->
<!--            <artifactId>jackson-annotations</artifactId>-->
<!--            <version>3.0-rc5</version>-->
<!--        </dependency>-->
    </dependencies>

    <build>
        <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
            <plugins>
                <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
                <plugin>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>3.1.0</version>
                </plugin>
                <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${plugin.maven.source.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${plugin.maven.resources.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${plugin.maven.compiler.version}</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                    </configuration>
                </plugin>

                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${plugin.surefire.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${plugin.maven.jar.version}</version>
                </plugin>
                <plugin>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>2.5.2</version>
                </plugin>
                <plugin>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>2.8.2</version>
                </plugin>
                <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
                <plugin>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.7.1</version>
                </plugin>
                <plugin>
                    <artifactId>maven-project-info-reports-plugin</artifactId>
                    <version>3.0.0</version>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>


</project>
