<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>jms-messenger</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>business-logic</module>
        <module>dao-api</module>
        <module>docker</module>
        <module>docker-artemis</module>
        <module>domain</module>
        <module>server</module>
        <module>integration-tests</module>
        <module>jms-client</module>
        <module>jms-api</module>
        <module>dao</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <hibernate-validator.version>8.0.1.Final</hibernate-validator.version>
    </properties>


    <dependencyManagement>
    <dependencies>

        <!-- Internal dependencies -->
        <dependency>
            <groupId>org.example</groupId>
            <artifactId>dao-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.example</groupId>
            <artifactId>dao</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.example</groupId>
            <artifactId>domain</artifactId>
            <version>${project.version}</version>
        </dependency>



        <!-- Jakarta Bean Validation API -->
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>3.0.2</version>
        </dependency>

        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>${hibernate-validator.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.hibernate/hibernate-tools -->
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-tools</artifactId>
            <version>5.6.15.Final</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
            <version>3.5.4</version>
        </dependency>
    </dependencies>
    </dependencyManagement>

</project>