services:
  msg-broker:
    image: apache/activemq-artemis:2.43.0
    container_name: msg-broker
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
      ARTEMIS_MIN_MEMORY: 512M
      ARTEMIS_MAX_MEMORY: 2048M
    ports:
      - "61616:61616"   # JMS
      - "8161:8161"     # Web console
    volumes:
      - ./runtime/artemis:/var/lib/artemis-instance   # optional but recommended
    networks:
      - msg_network

networks:
  msg_network:
    name: msg_network

